apiVersion: v1
kind: Secret
metadata:
  name: repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo
type: Opaque
stringData:
  url: git@github.com:sadhiqueali/infra-gitops-budget-app.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDVJBt0/0
    KpX8DtmEshTV6LAAAAGAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIAD9z00zUuFC0+db
    YkQ9/zKU+vsy6JvZi7/Gj3qjXN5PAAAAkIfTV1UbdUd3dtOE9cNiaaYRIBYxYVS2XkQjJ6
    9WwqP9XlD9IKK/S3rEdQyTnb1l6B4tlYjsrZ5YXMKgPVlPrKQy53tdfqo7KOEcRYC+OIjF
    DNrjO01CmodNIEHE6xL2Ikv9zmtGBii7oBaTXlHbaePl8qpOtWD7d1nC0W/TQxH8YC+qpA
    JLdzhv2Lw9K8IwCQ==
    -----END OPENSSH PRIVATE KEY-----
